[package]
name = "gemma"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.9.0"
candle-transformers = "0.9.0"
candle-nn = "0.9.0"
tokenizers = { version = "0.21.0", features = ["http"] }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
